(define (domain rover)

(:requirements :strips :typing :durative-actions :fluents :preferences)
(:types position robot)

(:predicates (at ?p - position ?r - robot)
            (busy ?r - robot)
            (connected ?p1 ?p2 - position)
            (communicated-with-earth ?p - position ?r - robot)
            (analysed-sample ?p - position ?r - robot)
            (taken-picture ?p - position ?r - robot)
            (drilled ?p - position ?r - robot)
            )

(:functions 
    (battery-level ?r -robot)
    (battery-required ?from ?to -  position)
    (battery-threshold ?r - robot)
)

(:durative-action take-picture 
:parameters (?p - position ?r - robot)
:duration (=?duration 5)
:condition (and (at start (not (busy ?r))) 
                (over all (at ?p ?r))
                (over all (not (taken-picture ?p ?r))))
:effect (and (at start (busy ?r))
             (at end (not(busy ?r)))
             (at end (taken-picture ?p ?r))
             )
)

(:durative-action drill
:parameters (?p - position ?r - robot)
:duration (= ?duration 20)
:condition (and (at start (not (busy ?r)))
                (over all (at ?p ?r))
                (over all (not(drilled ?p ?r))))
:effect (and (at start (busy ?r))
             (at end (not(busy ?r)))
             (at end (drilled ?p ?r)))  
)

(:durative-action communicate-with-earth
:parameters (?p - position ?r - robot)
:duration (= ?duration 10)
:condition (and (at start (not (busy ?r)))
           (over all (at ?p ?r))
           (over all (not (communicated-with-earth ?p ?r))))
:effect (and (at start (busy ?r))
             (at end (not(busy ?r)))
             (at end (communicated-with-earth ?p ?r))
             )  
)

(:durative-action analyse-sample
:parameters (?p - position ?r - robot)
:duration (= ?duration 15)
:condition (and (at start (not (busy ?r)))
                (over all (at ?p ?r))
                (over all (not (analysed-sample ?p ?r))))
:effect (and (at start (busy ?r))
             (at end (not(busy ?r)))
             (at end (analysed-sample ?p ?r))
             )  
)

(:durative-action extend-solar-panels
:parameters (?p - position ?r - robot)
:duration (= ?duration 50)
:condition (and (at start (not (busy ?r))) 
                (over all (at ?p ?r))
                (at start (< (battery-level ?r) (battery-threshold ?r)))
)
:effect (and (at start (busy ?r))
         (at end (not(busy ?r)))
         (at end (increase (battery-level ?r) 80))
)  
)

(:durative-action move-fast
    :parameters (?from ?to - position ?r -robot)
    :duration (= ?duration 20)
    :condition (and (at start(at ?from ?r))
                        (at start(not(busy ?r)))
                        (at start(>= (battery-level ?r)(* 2 (battery-required ?from ?to))))
                        (over all (connected ?from ?to)))
                        
    :effect (and (at start (not(at ?from ?r)))
                (at start (busy ?r)) 
                (at end(at ?to ?r))
                (at end (not (busy ?r)))
                (at end(decrease (battery-level ?r)(* 2 (battery-required ?from ?to))))
    )
)

(:durative-action move-slow
    :parameters (?from ?to - position ?r -robot)
    :duration (= ?duration 20)
    :condition (and (at start(at ?from ?r))
                        (at start(not(busy ?r)))
                        (at start(>= (battery-level ?r)(battery-required ?from ?to)))
                        (over all (connected ?from ?to)))
    :effect (and (at start (not(at ?from ?r)))
                (at start (busy ?r)) 
                (at end(at ?to ?r))
                (at end (not (busy ?r)))
                (at end (decrease (battery-level ?r)(battery-required ?from ?to)))
    )
)

)